# Small demo for testing of our model

In [19]:
import numpy as np
import pandas as pd
from sklearn.externals import joblib

In [20]:
our_model = joblib.load('finalized_model.sav') ## loading the XGBoost trained model

In [21]:
matches = pd.read_csv('demo.csv')

In [22]:
winner = pd.read_csv('winner.csv')

In [23]:
raw_data = pd.read_csv('raw_test_data.csv')

In [24]:
training_set = pd.read_csv('featured_test.csv')

## Match Data

In [25]:
matches

,Match_SK,Match_Id,Team1,Team2,match_date,Season_Year,Venue_Name,City_Name,Country_name_match,Toss_Winner,match_winner,Toss_Name,Win_Type,Outcome_Type,ManOfMach,Win_Margin,Country_id
0,566,981004,Royal Challengers Bangalore,Kings XI Punjab,5/18/2016,2016,M Chinnaswamy Stadium,Bangalore,India,Kings XI Punjab,Royal Challengers Bangalore,field,runs,Result,V Kohli,82.0,1
1,165,419161,Kings XI Punjab,Deccan Chargers,4/16/2010,2010,Himachal Pradesh Cricket Association Stadium,Dharamsala,India,Deccan Chargers,Deccan Chargers,field,wickets,Result,RG Sharma,5.0,1
2,355,598036,Kolkata Knight Riders,Kings XI Punjab,4/26/2013,2013,Eden Gardens,Kolkata,India,Kings XI Punjab,Kolkata Knight Riders,bat,wickets,Result,JH Kallis,6.0,1
3,474,829742,Royal Challengers Bangalore,Mumbai Indians,4/19/2015,2015,M Chinnaswamy Stadium,Bangalore,India,Royal Challengers Bangalore,Mumbai Indians,field,runs,Result,Harbhajan Singh,18.0,1
4,629,1082643,Gujarat Lions,Sunrisers Hyderabad,5/13/2017,2017,Green Park,Kanpur,India,Sunrisers Hyderabad,Sunrisers Hyderabad,Field,wickets,Result,Mohammed Siraj,8.0,1
5,442,734024,Delhi Daredevils,Kings XI Punjab,5/19/2014,2014,Feroz Shah Kotla,Delhi,India,Kings XI Punjab,Kings XI Punjab,field,wickets,Result,AR Patel,4.0,1
6,328,598009,Sunrisers Hyderabad,Royal Challengers Bangalore,4/7/2013,2013,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,India,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,Tie,Superover,GH Vihari,NaN,1
7,310,548375,Mumbai Indians,Kolkata Knight Riders,5/16/2012,2012,Wankhede Stadium,Mumbai,India,Mumbai Indians,Kolkata Knight Riders,field,runs,Result,SP Narine,32.0,1
8,465,829724,Royal Challengers Bangalore,Sunrisers Hyderabad,4/13/2015,2015,M Chinnaswamy Stadium,Bangalore,India,Sunrisers Hyderabad,Sunrisers Hyderabad,field,wickets,Result,DA Warner,8.0,1
9,499,829794,Chennai Super Kings,Mumbai Indians,5/8/2015,2015,"MA Chidambaram Stadium, Chepauk",Chennai,India,Chennai Super Kings,Mumbai Indians,bat,wickets,Result,HH Pandya,6.0,1
10,622,1082636,Royal Challengers Bangalore,Kolkata Knight Riders,5/7/2017,2017,M Chinnaswamy Stadium,Bengaluru,India,Kolkata Knight Riders,Kolkata Knight Riders,Field,wickets,Result,SP Narine,6.0,1
11,347,598028,Royal Challengers Bangalore,Rajasthan Royals,4/20/2013,2013,M Chinnaswamy Stadium,Bangalore,India,Royal Challengers Bangalore,Royal Challengers Bangalore,field,wickets,Result,R Vinay Kumar,7.0,1
12,386,598067,Chennai Super Kings,Delhi Daredevils,5/14/2013,2013,"MA Chidambaram Stadium, Chepauk",Chennai,India,Chennai Super Kings,Chennai Super Kings,bat,runs,Result,MS Dhoni,33.0,1
13,227,501256,Kings XI Punjab,Mumbai Indians,5/10/2011,2011,"Punjab Cricket Association Stadium, Mohali",Chandigarh,India,Mumbai Indians,Kings XI Punjab,field,runs,Result,BA Bhatt,76.0,1
14,417,729322,Mumbai Indians,Sunrisers Hyderabad,4/30/2014,2014,Dubai International Cricket Stadium,Abu Dhabi,U.A.E,Mumbai Indians,Sunrisers Hyderabad,field,runs,Result,B Kumar,15.0,3
15,240,501269,Kings XI Punjab,Deccan Chargers,5/21/2011,2011,Himachal Pradesh Cricket Association Stadium,Dharamsala,India,Kings XI Punjab,Deccan Chargers,field,runs,Result,S Dhawan,82.0,1
16,477,829748,Sunrisers Hyderabad,Kolkata Knight Riders,4/22/2015,2015,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,India,Kolkata Knight Riders,Sunrisers Hyderabad,field,runs,Result,DA Warner,16.0,1
17,602,1082616,Gujarat Lions,Kings XI Punjab,4/23/2017,2017,Saurashtra Cricket Association Stadium,Rajkot,India,Gujarat Lions,Kings XI Punjab,Field,runs,Result,HM Amla,26.0,1
18,306,548371,Kings XI Punjab,Deccan Chargers,5/13/2012,2012,"Punjab Cricket Association Stadium, Mohali",Chandigarh,India,Deccan Chargers,Kings XI Punjab,bat,wickets,Result,DJ Hussey,4.0,1
19,323,598004,Royal Challengers Bangalore,Mumbai Indians,4/4/2013,2013,M Chinnaswamy Stadium,Bangalore,India,Mumbai Indians,Royal Challengers Bangalore,field,runs,Result,CH Gayle,2.0,1

## Winners

In [26]:
winner

                   match_winner  encoded_teams
0   Royal Challengers Bangalore              2
1               Deccan Chargers              8
2         Kolkata Knight Riders              1
3                Mumbai Indians              7
4           Sunrisers Hyderabad              7
5               Kings XI Punjab              4
6           Sunrisers Hyderabad             11
7         Kolkata Knight Riders              1
8           Sunrisers Hyderabad             11
9                Mumbai Indians              7
10        Kolkata Knight Riders             13
11  Royal Challengers Bangalore              2
12          Chennai Super Kings              3
13              Kings XI Punjab              4
14          Sunrisers Hyderabad             11
15              Deccan Chargers              8
16          Sunrisers Hyderabad             11
17              Kings XI Punjab              4
18              Kings XI Punjab              4
19  Royal Challengers Bangalore              2

Feature engineering and data cleaning is performed on our dataset of matches. Further then, merging of players statistics with every match is done, and following dataframe is obtained, whcih can be treated as raw data for training our model

In [27]:
## After merging players statistics and matches dataset, we obtain following dataframe

In [28]:
raw_data

,Match_Id,Team1,Team2,City_Name,Venue_Name,Toss_Name,Toss_Winner,match_winner,Ave_batsman,SR_batsman,...,fast_scorer,consistent_batsman,run_betn_wkts,Econ,Wkt_Taker,consistent,big_wkt_taker,short_performance,SR,Ave
0,981004,2,4,2,14,0,4,2,0.104111,-1.144165,...,-1.144240,0.103766,-1.498817,0.770281,1.502753,1.052582,1.506629,1.514864,1.502714,1.052653
1,419161,4,8,11,10,0,8,8,0.147987,0.294881,...,0.294803,0.147709,0.802879,1.305821,1.179702,0.947027,1.716205,3.320816,1.179505,0.946998
2,598036,1,4,22,7,1,4,1,0.133979,-1.363311,...,-1.363374,0.134125,-0.659609,-0.530981,-0.436957,-0.516826,0.926529,-0.342672,-0.436946,-0.516972
3,829742,2,7,2,14,0,2,7,-0.592086,1.172860,...,1.173030,-0.592096,0.594702,0.890360,-0.628661,-0.416383,-0.141896,0.940031,-0.628745,-0.416499
4,1082644,1,7,22,7,0,1,7,0.620164,0.143722,...,0.143865,0.619706,0.352482,0.888136,0.542476,0.670423,-1.408748,-0.199822,0.542521,0.670446
5,734024,6,4,10,8,0,4,4,0.122171,1.101261,...,1.101151,0.121887,0.912855,-0.521687,-0.537231,-0.576920,-0.535556,0.256880,-0.537326,-0.576697
6,598009,11,2,14,25,1,2,11,-1.769232,-0.785376,...,-0.785387,-1.769187,-0.348502,-0.077195,-1.859263,-1.348255,0.041721,0.528721,-1.859196,-1.348207
7,548375,7,1,24,36,0,7,1,2.016316,1.710748,...,1.710612,2.016718,1.349517,0.030319,1.179223,1.235695,-0.600834,-0.287203,1.179378,1.235622
8,829724,2,11,2,14,0,11,11,0.164507,0.279804,...,0.279928,0.164492,1.143016,0.603332,-0.544600,-0.531816,-0.240827,1.589799,-0.544556,-0.531883
9,829794,3,7,8,15,1,3,7,-0.240375,-0.479267,...,-0.479162,-0.240744,-1.109230,-0.656591,-0.135785,0.244789,-0.729524,-0.052256,-0.135913,0.244853
10,1082637,4,13,23,21,0,13,13,-0.476730,-0.579450,...,-0.579387,-0.476853,-0.578931,1.402552,2.001666,1.921378,0.555321,0.199074,2.001865,1.921461
11,598028,2,5,2,14,0,2,2,-0.832955,-0.816115,...,-0.816079,-0.833263,-0.213145,-0.360999,1.242654,1.237437,-1.259560,-1.243710,1.242590,1.237500
12,598067,3,6,8,15,1,3,3,0.500068,-0.093907,...,-0.093859,0.500428,-0.069265,-0.850053,0.196670,0.115028,0.126035,-1.351706,0.196393,0.115092
13,501256,4,7,7,23,0,7,4,-1.204212,-0.377504,...,-0.377452,-1.203910,-0.015642,-0.291967,0.722714,0.832426,0.764145,-0.181709,0.722841,0.832469
14,729322,7,11,0,6,0,7,11,0.297123,0.029718,...,0.029875,0.296725,0.911895,1.039348,0.944282,0.797115,1.004680,1.279834,0.944329,0.797136
15,501269,4,8,11,10,0,4,8,-0.211160,-1.131831,...,-1.131942,-0.211428,0.241053,2.514029,0.570204,0.683624,-2.004637,0.828205,0.569917,0.683518
16,829748,11,1,31,5,0,1,11,-0.963361,-1.511386,...,-1.511260,-0.963838,-0.442098,0.246600,0.544622,0.585640,-1.188636,-0.036040,0.544495,0.585819
17,1082616,13,4,29,27,0,13,4,0.551538,1.312905,...,1.312903,0.551852,1.707514,-0.371217,-0.678479,-0.424366,-2.020454,-0.807031,-0.678502,-0.424375
18,548371,4,8,7,23,1,8,4,-0.021497,0.716053,...,0.716014,-0.021453,1.061424,-0.246134,-2.273115,-2.901214,0.456128,1.707723,-2.272901,-2.901174
19,598004,2,7,2,14,0,7,2,-0.099736,-0.574142,...,-0.574201,-0.099507,-0.502196,-0.776671,2.008022,1.738065,-1.079753,-1.450601,2.007788,1.737901

In [29]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 22 columns):
Match_Id              20 non-null int64
Team1                 20 non-null int64
Team2                 20 non-null int64
City_Name             20 non-null int64
Venue_Name            20 non-null int64
Toss_Name             20 non-null int64
Toss_Winner           20 non-null int64
match_winner          20 non-null int64
Ave_batsman           20 non-null float64
SR_batsman            20 non-null float64
hard_hitter           20 non-null float64
finisher              20 non-null float64
fast_scorer           20 non-null float64
consistent_batsman    20 non-null float64
run_betn_wkts         20 non-null float64
Econ                  20 non-null float64
Wkt_Taker             20 non-null float64
consistent            20 non-null float64
big_wkt_taker         20 non-null float64
short_performance     20 non-null float64
SR                    20 non-null float64
Ave                   20 non-null float64
dtypes: float64(14), int64(8)
memory usage: 3.5 KB

Transformation of training data after encoding categorical features and normalizing real valued features

In [30]:
training_set

,Toss_Name,Ave_batsman,SR_batsman,hard_hitter,finisher,fast_scorer,consistent_batsman,run_betn_wkts,Econ,Wkt_Taker,...,Toss_Winner_4,Toss_Winner_5,Toss_Winner_6,Toss_Winner_7,Toss_Winner_8,Toss_Winner_9,Toss_Winner_10,Toss_Winner_11,Toss_Winner_12,Toss_Winner_13
0,0,0.104111,-1.144165,-0.695716,-0.909015,-1.144240,0.103766,-1.498817,0.770281,1.502753,...,1,0,0,0,0,0,0,0,0,0
1,0,0.147987,0.294881,-0.156550,1.629056,0.294803,0.147709,0.802879,1.305821,1.179702,...,0,0,0,0,1,0,0,0,0,0
2,1,0.133979,-1.363311,-1.600155,0.085569,-1.363374,0.134125,-0.659609,-0.530981,-0.436957,...,1,0,0,0,0,0,0,0,0,0
3,0,-0.592086,1.172860,1.291963,-0.859570,1.173030,-0.592096,0.594702,0.890360,-0.628661,...,0,0,0,0,0,0,0,0,0,0
4,0,0.620164,0.143722,0.025507,-0.055938,0.143865,0.619706,0.352482,0.888136,0.542476,...,0,0,0,0,0,0,0,0,0,0
5,0,0.122171,1.101261,1.036923,1.053895,1.101151,0.121887,0.912855,-0.521687,-0.537231,...,1,0,0,0,0,0,0,0,0,0
6,1,-1.769232,-0.785376,-0.892930,-0.097873,-0.785387,-1.769187,-0.348502,-0.077195,-1.859263,...,0,0,0,0,0,0,0,0,0,0
7,0,2.016316,1.710748,1.610611,0.427642,1.710612,2.016718,1.349517,0.030319,1.179223,...,0,0,0,1,0,0,0,0,0,0
8,0,0.164507,0.279804,-0.343948,0.229196,0.279928,0.164492,1.143016,0.603332,-0.544600,...,0,0,0,0,0,0,0,1,0,0
9,1,-0.240375,-0.479267,0.027126,-0.579858,-0.479162,-0.240744,-1.109230,-0.656591,-0.135785,...,0,0,0,0,0,0,0,0,0,0
10,0,-0.476730,-0.579450,-0.528764,0.370214,-0.579387,-0.476853,-0.578931,1.402552,2.001666,...,0,0,0,0,0,0,0,0,0,1
11,0,-0.832955,-0.816115,-1.096394,-0.111034,-0.816079,-0.833263,-0.213145,-0.360999,1.242654,...,0,0,0,0,0,0,0,0,0,0
12,1,0.500068,-0.093907,-0.076465,-1.828324,-0.093859,0.500428,-0.069265,-0.850053,0.196670,...,0,0,0,0,0,0,0,0,0,0
13,0,-1.204212,-0.377504,-0.640572,0.569745,-0.377452,-1.203910,-0.015642,-0.291967,0.722714,...,0,0,0,1,0,0,0,0,0,0
14,0,0.297123,0.029718,-0.551343,0.165125,0.029875,0.296725,0.911895,1.039348,0.944282,...,0,0,0,1,0,0,0,0,0,0
15,0,-0.211160,-1.131831,-1.723785,-0.037999,-1.131942,-0.211428,0.241053,2.514029,0.570204,...,1,0,0,0,0,0,0,0,0,0
16,0,-0.963361,-1.511386,-1.933520,-0.103709,-1.511260,-0.963838,-0.442098,0.246600,0.544622,...,0,0,0,0,0,0,0,0,0,0
17,0,0.551538,1.312905,0.782895,1.217628,1.312903,0.551852,1.707514,-0.371217,-0.678479,...,0,0,0,0,0,0,0,0,0,1
18,1,-0.021497,0.716053,0.316908,0.762816,0.716014,-0.021453,1.061424,-0.246134,-2.273115,...,0,0,0,0,1,0,0,0,0,0
19,0,-0.099736,-0.574142,-0.504964,-1.568970,-0.574201,-0.099507,-0.502196,-0.776671,2.008022,...,0,0,0,1,0,0,0,0,0,0

In [31]:
##Number of training set features is quite large beacause of the encoding

## Predictions by XGBoost

In [32]:
predicted_winner = our_model.predict(training_set)

/opt/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

predicted winner is in encoded format

In [33]:
predicted_winner

array([ 2,  8,  1,  7,  1,  4, 11,  1, 11,  7, 13,  2,  3,  4, 11,  8, 11,
        4,  4,  2])

In [34]:
np.array(winner['encoded_teams'])

array([ 2,  8,  1,  7,  7,  4, 11,  1, 11,  7, 13,  2,  3,  4, 11,  8, 11,
        4,  4,  2])

In [35]:
accuracy = np.mean(predicted_winner == winner['encoded_teams'])

In [36]:
accuracy

0.95

Beacuse of the test data size is small here we have gotten accuracy more than we expected